version: '3.3'
services:
  blog-server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example